name: CI

on:
  push:
    branches:
      - main

jobs:
  run_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Installing dependencies
        run: yarn install
      - name: Run linting
        run: yarn lint
      - name: Run build
        run: yarn build
