name: CI

on:
  push:
    branches:
      - main

env:
  CF_SPACE_ID: ${{secrets.CF_SPACE_ID}}
  CF_ACCESS_TOKEN: ${{secrets.CF_ACCESS_TOKEN}}
  NEXT_PUBLIC_EMAILJS_SERVICE_ID: test
  NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: test
  NEXT_PUBLIC_EMAILJS_USER_ID: test
  NEXT_PUBLIC_GOOGLE_ANALYTICS: test

jobs:
  run_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Installing dependencies
        run: yarn install
      - name: Run linting
        run: yarn lint
      - name: Run build
        run: yarn build
